import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import Banner from "../components/Home/sections/Banner";
import BestSellers from "../components/Home/sections/BestSellers";
import Newsletters from "../components/Home/sections/Newsletters";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Corebiz - Frontend Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className={styles.container}>
        <main className={styles.main}>
          <Banner />

          <BestSellers />

          <Newsletters />
        </main>
      </div>

      <Footer />
    </>
  );
};

export default Home;
